### ISSUE TITLE
Demo file crahes

### ISSUE THREAD

**Issue by ghost** [liruoteng/OpticalFlowToolkit#1]
Hi liruoteng!
I'm currently trying to display the .flo files.
To do so i went throught your nice toolikt, got it setup on my desk and unfortunately I get the following error while launching the "python demo.py" :

Traceback (most recent call last):
  File "demo.py", line 12, in <module>
    flow = kittitool.flow_read(flow_file)
AttributeError: 'module' object has no attribute 'flow_read'

Thanks in advance for your support :D !
Cheers

**Comment by liruoteng** [comment]
Hi @UntakenUserNameIsTaken  sorry about the issue. 

I forgot to update the demo file when I pushing the changes for flow lib
You may want to use this changeset `f90d5e00`
