### ISSUE TITLE
A Problem of png Files

### ISSUE THREAD

**Issue by huaxiaojian1997** [liruoteng/OpticalFlowToolkit#14]
Hi, @liruoteng 
thank you for your sharing, I installed OpticalFlowToolkit according to your instructions. I successfully visualized the. flo file and converted it to png file, but I encountered a problem, I found the lower part of the picture was covered. I am not sure what this is. Can you help me?
![myplot_first second](https://user-images.githubusercontent.com/38944316/54600565-0744ef80-4a78-11e9-9e73-d7186df10c39.png)
![myplot_frame1 frame2](https://user-images.githubusercontent.com/38944316/54600566-07dd8600-4a78-11e9-98b9-81940f145403.png)

**Comment by liruoteng** [comment]
Hi @huaxiaojian1997 , sorry for the late reply. 
May I see your code please?

Thanks

**Comment by huaxiaojian1997** [comment]
Hello, I'm sorry for the late reply.
I only changed one line of code in the program, which was previously reported as an error:  

File "D:/OpticalFlowToolkit-master/OpticalFlowToolkit-master/demo.py", line 20, in <module>
    flow_Middlebury = fl.read_flow(flow_file_Middlebury)
  File "D:\OpticalFlowToolkit-master\OpticalFlowToolkit-master\lib\flowlib.py", line 91, in read_flow
    flow = read_flo_file(filename)
  File "D:\OpticalFlowToolkit-master\OpticalFlowToolkit-master\lib\flowlib.py", line 541, in read_flo_file
    data2d = np.fromfile(f, np.float32, count=2 * w * h)
TypeError: only integer scalar arrays can be converted to a scalar index

Therefore, I changed data2d = np.fromfile (f, np.float32, count = 2 * w * h) to data2d = np.fromfile (f, np.float32, count = 2 * 584 * 388).

**Comment by huaxiaojian1997** [comment]
Hi, @liruoteng, I have solved this problem, thank you for your help.
