### ISSUE TITLE
Rgb2floFiles

### ISSUE THREAD

**Issue by 3DMM-ICME2023** [liruoteng/OpticalFlowToolkit#2]
Hi，Thanks for your sharing!
I want to change a color optical flow image(3 channels) to .flo files ,so that i can evaluate it with my own .flo
files,Did you write the function before?Thank you very much!

**Comment by liruoteng** [comment]
Hi In that case, the converted flow will be very inaccurate. I did not write that function, neither do I think it useful.  If you really need it, you may do reverse-engineering on the flow_to_image function of lib/flowlib.py. Thanks!
