### ISSUE TITLE
Warping image type error

### ISSUE THREAD

**Issue by rubychilds** [liruoteng/OpticalFlowToolkit#3]
There's a type error between image and flow when in warping `warp_image` line 395 

`TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'`

Can fix by adding `fl = fl.astype('int64')`

**Comment by rubychilds** [comment]
Another issue in `warp_image` involves axis out of bounds, line 398 `fx = np.min(np.max(fx, 0), flow_width)`

ValueError: 'axis' entry is out of bounds

Note, I used sample files, `data/example/flow_gt.flo` and `data/example/flow_gt.png`

**Comment by liruoteng** [comment]
Hi @rubychilds , sorry for the very late reply as I was busy with other staffs during these days... Thank you for pointing our the problem that I have in the function. I have already fixed them in the latest changeset. `6c126029`

Thank you!
